/// Primary calendar dimension table for time-based reporting. Supports period, quarter, month, and year analysis for hiring, active headcount, and separations.
table Date
	lineageTag: fcf95b56-e617-491e-893f-00e4597e641c
	dataCategory: Time

	/// Counts date records in the current filter context.
	measure 'Count of Date' = COUNTA('Date'[Date])
		lineageTag: e09ec19a-59d1-4017-b5c6-3088c07ae36a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Calendar date used as the primary date key for time intelligence.
	column Date
		dataType: dateTime
		isKey
		formatString: General Date
		lineageTag: ad72503a-626e-4f7f-bf6b-30637a1c5dea
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 0f809af4-d31b-4977-a214-8f13fa42f41d
			defaultHierarchy: LocalDateTable_6f19fed3-1fc0-4f7a-878d-34aca93d6782.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Month name used in period-based reporting.
	column Month
		dataType: string
		lineageTag: 44a9ad95-6530-4678-b989-9749fe691670
		summarizeBy: none
		sourceColumn: Month
		sortByColumn: MonthNumber

		annotation SummarizationSetBy = Automatic

	/// Numeric month used to sort month names in calendar order.
	column MonthNumber
		dataType: int64
		lineageTag: 69138651-3695-4545-afd4-a647cb122e7b
		summarizeBy: sum
		sourceColumn: MonthNumber

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Reporting period label (for example Jan 2013) for month-level analysis.
	column Period
		dataType: string
		lineageTag: fa550177-7149-47fa-be77-554d299f042f
		summarizeBy: none
		sourceColumn: Period
		sortByColumn: PeriodNumber

		annotation SummarizationSetBy = Automatic

	/// Sequential period number used for chronological sorting and latest-period logic.
	column PeriodNumber
		dataType: int64
		lineageTag: 8234d3c8-1d33-4df9-8a6a-daaaa459afc2
		summarizeBy: sum
		sourceColumn: PeriodNumber

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Quarter number within the year.
	column Qtr
		dataType: int64
		lineageTag: 1fb80d69-2b87-4e88-97a9-2c3b60e7aace
		summarizeBy: sum
		sourceColumn: Qtr

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Quarter label used in reporting hierarchies.
	column QtrNumber
		dataType: string
		lineageTag: 09e4ae29-92ea-42c4-a7d8-97de8dc81e21
		summarizeBy: none
		sourceColumn: QtrNumber

		annotation SummarizationSetBy = Automatic

	/// Calendar year number.
	column Year
		dataType: int64
		lineageTag: 56b46769-d33d-4aa8-82f9-9824fd146251
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Day of month number.
	column Day
		dataType: int64
		lineageTag: 4fd1f5a8-500e-4603-b019-5e60fb3163ea
		summarizeBy: sum
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// First calendar date of the month for each row date.
	column MonthStartDate
		dataType: dateTime
		formatString: General Date
		lineageTag: b406a759-c35f-4f27-9ae3-c13f61f49d9c
		summarizeBy: none
		sourceColumn: MonthStartDate

		variation Variation
			isDefault
			relationship: f496f9ad-5665-4785-a30e-b1bbcf7be215
			defaultHierarchy: LocalDateTable_d2ea5b26-668d-4c17-b228-695669b066a6.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Last calendar date of the month for each row date.
	column MonthEndDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 94efa1ef-6993-47f0-8e98-adbdb6de4029
		summarizeBy: none
		sourceColumn: MonthEndDate

		variation Variation
			isDefault
			relationship: b2a9d346-0212-432d-a1a9-57680b4a73ea
			defaultHierarchy: LocalDateTable_c9dde99e-7ac1-4e8e-a5f2-c5ffc41d9cac.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Calculated month index from model start used for relative month calculations.
	column MonthIncrementNumber = ([Year]-MIN([Year]))*12 +[MonthNumber]
		isHidden
		lineageTag: c01f1989-027f-4f34-9698-4efdcc269f00
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	hierarchy YQM
		lineageTag: 2d0ba6c3-0b1b-4cea-93bd-688956e54a7c

		level Year
			lineageTag: 58deddc6-f101-4863-9fe3-151b3d07f5cb
			column: Year

		level QtrNumber
			lineageTag: f4b7f26d-f884-4068-9bef-e6f1d625c3a5
			column: QtrNumber

		level PeriodNumber
			lineageTag: c00652af-af6c-42e5-a2a6-d408f7f8cbe8
			column: PeriodNumber

	partition Date = m
		mode: import
		source =
				let
				    Source = Sql.Database(".", "IP", [Query="SELECT [HR].[Date].*   FROM [HR].[Date]"]),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"Date", "Date"}, {"Month", "Month"}, {"MonthNumber", "MonthNumber"}, {"Period", "Period"}, {"PeriodNumber", "PeriodNumber"}, {"Qtr", "Qtr"}, {"QtrNumber", "QtrNumber"}, {"Year", "Year"}, {"Day", "Day"}, {"MonthStartDate", "MonthStartDate"}, {"MonthEndDate", "MonthEndDate"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns", {{"Date", type datetime}, {"Month", type text}, {"MonthNumber", Int64.Type}, {"Period", type text}, {"PeriodNumber", Int64.Type}, {"Qtr", Int64.Type}, {"QtrNumber", type text}, {"Year", Int64.Type}, {"Day", Int64.Type}, {"MonthStartDate", type datetime}, {"MonthEndDate", type datetime}})
				in
				    #"Changed Type"

	annotation __PBI_LegacyCustomDateTable = true

